# config.yaml
model:
  dim_in: 2
  dim_hidden: 256
  dim_out: 1
  n_hidden_layers: 5
  w0: 30

training:
  n_epochs: 100
  lr: 0.01
  resolution: 28

paths:
  data_dir: "/home/tempus/projects/data/mnist"
  results_dir: "/home/tempus/projects/siren_analysis/siren_encodings/mnist"